listen: &tls_listener
  port: 8443
  ssl:
    certificate-file: /etc/h2o/certs/localhost.crt
    key-file: /etc/h2o/certs/localhost.key
    minimum-version: TLSv1.3
    ocsp-update-interval: 0

listen:
  <<: *tls_listener
  type: quic

hosts:
  "localhost": &protocol_lab_host
    paths:
      /status:
        file.file: /srv/h2o/status.json
      /bytes/1024:
        file.file: /srv/h2o/bytes/1024.bin
      /bytes/65536:
        file.file: /srv/h2o/bytes/65536.bin
  "host.docker.internal":
    <<: *protocol_lab_host
  "plab-worker-sut-01":
    <<: *protocol_lab_host
  "plab-worker-load-01":
    <<: *protocol_lab_host

access-log: /dev/stdout
error-log: /dev/stderr
