server:
  verbosity: 1
  username: "_unbound"
  directory: "/opt/unbound/etc/unbound"
  chroot: ""
  pidfile: "/tmp/unbound.pid"
  interface: 0.0.0.0@443
  do-udp: yes
  do-tcp: yes
  do-ip4: yes
  do-ip6: no
  access-control: 0.0.0.0/0 allow
  https-port: 443
  http-endpoint: "/dns-query"
  tls-service-key: "/opt/unbound/etc/unbound/plab/leaf-key.pem"
  tls-service-pem: "/opt/unbound/etc/unbound/plab/leaf.pem"
  tls-session-ticket-keys: ""
  hide-identity: yes
  hide-version: yes
  qname-minimisation: no
  prefetch: no
  serve-expired: no
  cache-min-ttl: 0
  cache-max-ttl: 0
  infra-cache-numhosts: 1
  do-not-query-localhost: no
  module-config: "validator iterator"
  val-permissive-mode: no
  domain-insecure: "plab.test."
  local-zone: "test." nodefault
forward-zone:
  name: "plab.test."
  forward-addr: 127.0.0.1@5353
  forward-first: no

remote-control:
  control-enable: yes
  control-interface: 127.0.0.1
  control-port: 8953
  control-use-cert: no
