options {
  directory "/var/cache/bind";
  pid-file "/var/cache/bind/authority.pid";
  session-keyfile "/var/cache/bind/authority-session.key";
  recursion no;
  allow-query { any; };
  minimal-responses yes;
  dnssec-validation no;
  listen-on-v6 { none; };
  listen-on port 5353 { 127.0.0.1; };
};
controls { };
zone "plab.test" { type primary; file "/etc/bind/plab/db.plab.test"; allow-query { any; }; };
