options { directory "/var/cache/bind"; recursion no; minimal-responses yes; dnssec-validation no; allow-query { any; }; listen-on-v6 { none; }; listen-on port 853 tls plab-tls { any; }; };
tls plab-tls { key-file "/etc/bind/plab/leaf-key.pem"; cert-file "/etc/bind/plab/leaf.pem"; protocols { TLSv1.3; }; };

zone "plab.test" { type primary; file "/etc/bind/plab/db.plab.test"; allow-query { any; }; };
