options {
  directory "/var/cache/bind";
  recursion no;
  minimal-responses yes;
  dnssec-validation no;
  allow-query { any; };
  listen-on port 53 { any; };
  listen-on-v6 { none; };
};

zone "plab.test" {
  type primary;
  file "/etc/bind/plab/db.plab.test";
  allow-query { any; };
};
